FORMAT: 1A
HOST: http://api.bombbomb.com

# BombBomb
The BombBomb API controls email creation, sending and tracking within the BombBomb system..

## Conventions
This API attempts to follow RESTful constraints. In cases where the standard HTTP verbs (GET, PUT, POST, DELETE) are not good descriptors of functionality, we may expose a controller resource. Controllers, by convention will begin with a tilde (~).

So, a DELETE call to the resource /clients/c-1/lists/list-3/contact-2 will remove the actual contact resource as per the definition of DELETE. You may POST a *remove-contacts* task to the list controller instead to remove the contact from the list itself: POST /clients/c-1/lists/list-3/~remove-contacts?contacts[]=contact-2
## Authentication
The **Bombbomb API** can be authenticated via a session token retrieved from the /authentication resource, or by an API_Key. 

Almost every resource except for /clients:POST, /email-jobs/{job-id}:GET, and /vidoes/{video-id}:GET requires authentication.

## Media Types
Where applicable this API uses the [HAL+JSON](https://github.com/mikekelly/hal_specification/blob/master/hal_specification.md) media-type to represent resources states and affordances.

Requests with a message-body are using plain JSON to set or update resource states.

# Group Client
Client related resources of the **Bombbomb API**

## Client [/clients/{id}]
A single Client object. 

- id
- name
- created_at
- login_email

The states *id* and *created_at* are assigned by the **BombBomb API** at the moment of creation. 

+ Parameters
    + id (Guid) ... ID of the Client in the form of a Guid.

+ Model (application/hal+json)

    HAL+JSON representation of Gist Resource. In addition to representing its state in the JSON form it offers affordances in the form of the HTTP Link header and HAL links.

    + Headers

            Link: <http:/api.bombbomb.com/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa>;rel="self"

    + Body

            {
                "_links": {
                    "self": { "href": "/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa" },
                },
                id: "cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa",
                created_at: "2014-01-02T07:15:15+00:00",
                name: "Fantastic Marketeers",
                login_email: "fan.market@gmail.com",
                status: "ACTIVE",
                subscription: ""
            }

### Retrieve a Single Client [GET]
+ Response 200
    
    [Client][]

### Create a Client [POST]

This will create a BombBomb client assuming that the login_email is not currently associated with an existing client.

A client is initially given a FREE_TRIAL subscription. This can be changed by PUTing a payment method and then PUTing and alternative subscription plan.

+ Request (application/json)

        { 
            login_email: "new.user@mail.com",
            name: "Real Scrappy Realtors",
        }

+ Response 201 (application/json)

        {
            "_links": {
                "self": { "href": "/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa" },
            },
            id: "cccccccc-3333-aaaa-aaaa-aaaaaaaaaaaa",
            created_at: "2014-01-09T16:22:03-07:00",
            name: "Fantastic Marketeers",
            login_email: "fan.market@gmail.com",
            status: "ACTIVE"
        }

## Contact [/clients/{id}/contacts/{id|email}]
A single Contact object. 

- id
- email
- first_name
- last_name
- add_date
- sendable [true/false]
- opt_out [true/false]
- suppressed [true/false]
- marked_abuse [true/false]
- last_bounce
- hard_bounce_count
- soft_bounce_count
- engagement_score

+ Parameters
    + id (Guid, required) ... ID of the Contact in the form of a Guid.


+ Model (application/hal+json)

    HAL+JSON representation of Gist Resource. In addition to representing its state in the JSON form it offers affordances in the form of the HTTP Link header and HAL links.

    + Headers

            Link: <http://api.bombbomb.com/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa/contacts/cccccccc-5555-aaaa-aaaa-aaaaaaaaaaaa>;rel="self">

    + Body

            {
                "_links": {
                    "self": { "href": "/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa/contacts/cccccccc-5555-aaaa-aaaa-aaaaaaaaaaaa" },
                },
                id: "cccccccc-5555-aaaa-aaaa-aaaaaaaaaaaa",
                email: "someone@gmail.com",
                first_name: "Jim",
                last_name: "Stone",
                add_date: "2014-01-02T07:15:15+00:00",
                sendable: true,
                opt_out: false,
                suppressed: false,
                marked_abuse: false,
                last_bounce: {
                    date: "2013-11-02T07:15:15+00:00",
                    code: "5.2.1",
                    diagnostic: "smtp;550 5.2.1 The user you are trying to contact is receiving mail at a rate that prevents additional messages from being delivered. For more information, please visit http://support.google.com/mail/bin/answer.py?answer=6592 d10si20135078vdv.15 - gsmtp"
                },
                hard_bounce_count: 0,
                soft_bounce_count: 3,
                engagement_score: 2,
                status: "ACTIVE",
                subscription: ""
            }

### Retrieve a Single Client [GET]
+ Response 200
    
    [Contact][]



## Contact-Lists Collection [/clients/{id}/contact-lists]
Retrieves a collection of all the client's lists 

The List Collection resource has the following attribute:

- total

In addition it **embeds** *Contact-List Resources* in the BombBomb API.

+ Model (application/hal+json)

    HAL+JSON representation of Client Collection Resource. The Client resources in collections are embedded. Note the embedded Clients resource are incomplete representations of the Client in question. Use the respective Client link to retrieve its full representation.

    + Headers

            Link: <http://api.bombbomb.com/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa/contact-lists>;rel="self"

    + Body

            {
                _links: {
                    self: { "href": "/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa/contact-lists" }
                },
                _embedded: {
                    contact-lists: [
                        {
                            _links : {
                                self: { "href": "/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa" }
                            },
                            id: "cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa",
                            created_at: "2014-01-02T07:15:15+00:00",
                            name: "Fantastic Marketeers",
                            login_email: "fan.market@gmail.com",
                            status: "ACTIVE"
                        },
                        {
                            _links : {
                                self: { "href": "/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa" }
                            },
                            id: "cccccccc-2222-aaaa-aaaa-aaaaaaaaaaaa",
                            created_at: "2013-11-05T08:15:15+00:00",
                            name: "Adequate Advertisers",
                            login_email: "ads_r_us@yahoo.com",
                            status: "EXPIRED"
                            
                        },
                    ]
                },
                total: 2
            }
            
### List all Contact-Lists [GET]

+ Response 200

    [Contact-Lists Collection][]
    
## Clients Collection [/clients{?since}]
Collection of all Clients.

The Client Collection resource has the following attribute:

- total

In addition it **embeds** *Client Resources* in the BombBomb API.

+ Model (application/hal+json)

    HAL+JSON representation of Client Collection Resource. The Client resources in collections are embedded. Note the embedded Clients resource are incomplete representations of the Client in question. Use the respective Client link to retrieve its full representation.

    + Headers

            Link: <http:/api.bombbomb.com/clients>;rel="self"

    + Body

            {
                _links: {
                    self: { "href": "/clients" }
                },
                _embedded: {
                    clients: [
                        {
                            _links : {
                                self: { "href": "/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa" }
                            },
                            id: "cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa",
                            created_at: "2014-01-02T07:15:15+00:00",
                            name: "Fantastic Marketeers",
                            login_email: "fan.market@gmail.com",
                            status: "ACTIVE"
                        },
                        {
                            _links : {
                                self: { "href": "/clients/cccccccc-1111-aaaa-aaaa-aaaaaaaaaaaa" }
                            },
                            id: "cccccccc-2222-aaaa-aaaa-aaaaaaaaaaaa",
                            created_at: "2013-11-05T08:15:15+00:00",
                            name: "Adequate Advertisers",
                            login_email: "ads_r_us@yahoo.com",
                            status: "EXPIRED"
                            
                        },
                    ]
                },
                total: 2
            }
            
### List all Clients [GET]

+ Parameters
    + since (optional, string) ... Timestamp in ISO 8601 format: `YYYY-MM-DDTHH:MM:SS+00:00` Only clients created at or after this time are returned. Defaults to one week previous.

+ Response 200

    [Clients Collection][]
    


# Group Emails
Email related resources of the **Bombbomb API**

## Emails Collection [/emails]
### List all Emails [GET]

- id
- title
- description
- content

+ Response 200 (application/json)

        [{
          "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
          "title": "Jogging in park"
        }, {
          "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab",
          "title": "Pick-up posters from post-office"
        }]

### Create an Email [POST]
+ Request (application/json)

        {
            "title": "Buy cheese and bread for breakfast."
        }

+ Response 201 (application/json)

        { "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac", "title": "Buy cheese and bread for breakfast." }

## Email [/emails/{id}]
A single Email object with all its details

- id
- title
- description
- content

+ Parameters
    + id (required, guid, `aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa`) ... Guid `id` of the Email to perform action with. Has example value.

### Retrieve an Email [GET]

+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
                "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab",
                "title": "Pick-up posters from post-office"
            }

### Remove an Email [DELETE]
+ Response 204



## Email Tracking [/emails/tracking/{id}]
Retrieve email tracking details

- id
- title
- description
- content

+ Parameters
    + id (required, guid, `aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa`) ... Guid `id` of the Email to perform action with. Has example value.

### Retrieve tracking details on Email [GET]

+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
                "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab",
                "title": "Pick-up posters from post-office"
            }








# Group Videos
Video related resources of the **Bombbomb API**

## Videos Collection [/videos]
### List all Videos [GET]
+ Response 200 (application/json)

        [{
          "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa", "title": "Jogging in park"
        }, {
          "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab", "title": "Pick-up posters from post-office"
        }]

### Create a Video [POST]
+ Request (application/json)

        { 
            title: "Great House on Broadway",
            original_src: "s3.bombbomb.com/uploads/dddddd-aaaa-1111-abcdef.mpg"
        }

+ Response 201 (application/json)

        { "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac", "title": "Buy cheese and bread for breakfast." }

## Video [/videos/{id}]
Retrieve a single Video object with all its details. The Video resource has the following attributes:

- id
- title
- description
- content


+ Parameters
    + id (required, string, `aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa`) ... Guid `id` of the Video to perform action with. Has example value.

### Retrieve an Video [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab", "title": "Pretty funny video" }

### Update Video Details [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab", "title": "Pretty funny video" }

